### ISSUE TITLE
Converting to hdf5

### ISSUE THREAD

**Issue by andersdot** [rainwoodman/bigfile#20]
@rainwoodman and @sbird 
I see you guys have some code to convert from hdf5 to bigfile, but do you have any code to do the reverse? I have some analysis code that takes hdf5 as input that I want to run on outputs from MP-Gadget, where that outputs are only a few GB. Thanks :)

**Comment by andersdot** [comment]
Nevermind ! The analysis code takes bigfile

**Comment by sbird** [comment]
We should probably implement such a script anyway!

(What are you using MP-Gadget for?)

**Comment by andersdot** [comment]
I'm working with @andreufont and @apontzen running lya boxes. We're trying to see if @apontzen's paired galaxy sims can help constrain cosmology via lya, it's only been tested with dm so far.

**Comment by sbird** [comment]
Ok - I assume you are using my fake_spectra code for analysis? (because that is almost the only analysis code that takes bigfile :) ). Good luck, and we will try to fix the bugs you are finding.

**Comment by rainwoodman** [comment]
We now do have this that supports limited conversion from and to bigfile and FITS files.

https://github.com/rainwoodman/bigfile/blob/master/scripts/bigfile-convert

I am closing this ticket, partly to advertise the tool, too.
