### ISSUE TITLE
Installation Error with pip

### ISSUE THREAD

**Issue by zovelsanj** [rainwoodman/bigfile#44]
I am trying to install `bigfile` in Python. I tried `pip install bigfile` (in both Python3.8 and 3.10) like suggested in the `Readme.md`. But i am consistently getting `ModuleNotFoundError: No module named 'Cython'` error. I have `Cython` installed which i further verified with as follows:

```
>>> from Cython.Build import cythonize
>>> print(dir(cythonize))
['__annotations__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```

The complete error log is as follows:
```
Collecting bigfile
  Using cached bigfile-0.1.51.tar.gz (221 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "c:\users\ekser\documents\research-works\astrophysics\bigfile\build\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\users\ekser\documents\research-works\astrophysics\bigfile\build\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\ekser\documents\research-works\astrophysics\bigfile\build\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ekser\AppData\Local\Temp\pip-build-env-a5wu1t5e\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\ekser\AppData\Local\Temp\pip-build-env-a5wu1t5e\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\ekser\AppData\Local\Temp\pip-build-env-a5wu1t5e\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'Cython'

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

I thought the error was in Windows only, so i tried installing in Linux (22.04) but the error is exactly the same.

**Comment by zovelsanj** [comment]
I think the error is with the pip package: it looks for `C` header files.

```
    bigfile.c
    src/bigfile.c(5): fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory
```

Shouldn't pip package directly import all its requirements? Why is it looking for header files? 

By the way, installing from source and then from pip worked for me. But why doesn't `pip install bigfile` work without installation from source? And if one needs to install from source then what is the point of using pip package?

**Comment by rainwoodman** [comment]
It is probably because pip used a different compiler / CFLAGS setting (usually it picks up from a Python configuration file) than when you install from the source. Tracking that down can be a bit difficult however (at least I don't recall how to do it anymore.)

I just tried a similar set of steps from a fresh virtualenv: after pip install numpy cython, I could run pip install bigfile and it worked. This was on a Fedora box. Unfortunately I have lost track which compiler packages I have installed, most likely just the usual ones provided by the distribution.

Google search for the alloca.h error seems to mention that the error tends to be from Windows, as the header is usually not available on windows systems. I have never compiled bigfile on Windows, so some glitches like this is likely expected. That said there is no hard requirement to use alloca in bigfile: if you go through the code and replace alloca usage with malloc + free, I think you can get around this error.

**Comment by zovelsanj** [comment]
> It is probably because pip used a different compiler / CFLAGS setting (usually it picks up from a Python configuration file) than when you install from the source. Tracking that down can be a bit difficult however (at least I don't recall how to do it anymore.)
> 
> I just tried a similar set of steps from a fresh virtualenv: after pip install numpy cython, I could run pip install bigfile and it worked. This was on a Fedora box. Unfortunately I have lost track which compiler packages I have installed, most likely just the usual ones provided by the distribution.
> 
> Google search for the alloca.h error seems to mention that the error tends to be from Windows, as the header is usually not available on windows systems. I have never compiled bigfile on Windows, so some glitches like this is likely expected. That said there is no hard requirement to use alloca in bigfile: if you go through the code and replace alloca usage with malloc + free, I think you can get around this error.

Thank you @rainwoodman. Actually, this makes sense, I was trying to install bigfile in Windows as I had few Windows dependencies to work with. Since I installed it from the source, its working good in virtual environment. But thank you for pointing out the issue.
